MikaelFangel/nixvim-config

config/autosave.nix, config/default.nix
Add the auto save feature, which is loaded by default and triggers on leaving insert mode.
=> autosave: init

config/auto-pairs.nix, config/default.nix
Adds auto-closing brackets, also called autopairs.
=> auto-pairs: init

config/options.nix
* Enable saving undotree between buffer sessions
* Enable autoindent
* Makes search case incensitive + enable smart searc 
* Enables incremental searches
* Speeds-up the autocompletion windows
=> options: persistence and ux

config/lsp.nix
Change to a better supported nix lsp which isn't in a beta state.
=> lsp: swap rnix-lsp with nixd

config/default.nix
Title sums up the extent of the feature.
=> Added keymap to escape terminal mode using ESC

config/default.nix, config/none-ls.nix, flake.lock
* Updates the flake and renamed null-ls to none-ls, due to community adoption.
=> flake: update

config/none-ls.nix, flake.lock
* Updates flake.lock to expose change from nixvim
* Adds the fantomas formatter
=> fantomas: init

config/lsp.nix, shell.nix
Enable elixir_ls and add elixir to the dev shell.
=> elixir: init

config/none-ls.nix
=> gofmt: init

config/lsp.nix, config/none-ls.nix, flake.lock, shell.nix
* Enable ktlint for diagnostics and formatting
* Enable the kotlin-language-server
* At kotlin compiler to shell
* The kotlin-language-server and ktlint is CPU intensive, so it might timeout on low perfomance CPU's
=> ktlint: enable; kotlin-language-server: enable

flake.lock
* Update the flake.lock file
The lock should be updated to include the latest fixes for fsautocomplete so it works again.
=> flake: update lock

config/none-ls.nix, flake.lock
* Enable goimports for formatting
* Update flake.lock to receive changes from upstream
=> goimports: init

config/git.nix, config/options.nix
- Update git and options to fit upstream changes.
=> git: update settings

README.md
- Corrected the spelling of the readme file.
=> readme: corrected spelling

config/default.nix
- Remap the leader to spacebar
=> globals: remap leader to spacebar

config/cmp.nix
- Fixes #54 by configuring luasnip according to the docs: [https://nix-community.github.io/nixvim/plugins/cmp/extraOptions/snippet.html](https://nix-community.github.io/nixvim/plugins/cmp/extraOptions/snippet.html)
=> cmp: fixed issue where lusnip reported error

config/default.nix
- Added keymaps for gitsigns.
- Added keymaps for tabs.
=> keymaps: add keymaps for gitsigns and tabs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> issue: add templates

.github/workflows/build.yml
- Updates the nix action version
- Updates the cachix action version
=> actions: update versions

config/default.nix
- Add key to reset hunk 
- Add key to reset buffer 
See the wiki for full list of keymaps: https://github.com/MikaelFangel/nixvim-config/wiki/Key-Mappings
=> keys: add more keys for gitsigns

config/default.nix
- **keys: add more keys for gitsigns**
- **fmt: tree format**
=> key: add more keys

config/blankline.nix, config/default.nix
- Enabled indent-blankline
CC: @PhilipCramer, @Greve2001, @yech199 - For opinions.
=> blankline: init

README.md, config/default.nix, config/fidget.nix
- Enabled fidget
CC: @PhilipCramer, @Greve2001, @yech199 - For opinions.
=> fidget: init

config/options.nix
- Make buffer split to the right and below
- Keep 4 lines on screen while scrolling
=> options: improve splitting and scrolling

config/cmp.nix, config/lsp/default.nix, config/lsp/none-ls.nix, shell.nix
Gleam has recently become production ready and thus is a nice addition for when writing Elixir programs.
- Enable gleam lsp
- Enable gleam format
- Add gleam to the shell file
=> gleam: init

config/default.nix, config/lsp/default.nix
- Adds the prolog-ls
- Make .pl file detect as the filetype prolog (could be improved in the future maybe)
To get prolog-ls running you first need to run the following using swipl: 
```prolog
?- pack_install(lsp_server).
```
CC @PhilipCramer
=> lsp: init prolog

config/cmp.nix
- Make up and down work as intended.
=> cmp: switch up and down keys

config/utils/autosave.nix
- Renames option according to upstream.
=> autosave: rename option accorinding to upstream

config/lsp/none-ls.nix
- Add credo for Elixir diagnostics
=> none-ls: add credo

config/lightline.nix
- Add the material theme to lightline
=> lightline: add material theme

config/default.nix
- Fix the trouble toggle command so the keymap works again.
=> keymap: fix trouble toggle

config/default.nix, config/utils/lazygit.nix
=> lazygit: init

flake.lock
=> build(deps): update flake.lock
